### ISSUE TITLE
Is the OpenSSF hosted instance viable for commercial use?

### ISSUE THREAD

**Issue by ArisBee** [ossf/allstar#310]
Hi there,

I would like to know if the version of Allstar hosted by the OpenSSF is viable to be configured in my company's GitHub organization?

I also see below that it requires administration write permissions? Which I see isn't part of the configuration shown in the [self-deployment tutorial](https://github.com/ossf/allstar/blob/main/operator.md).

![image](https://user-images.githubusercontent.com/18463777/200557221-6b3a3465-4c83-4707-8243-206c0ca5358a.png)

**Comment by jeffmendoza** [comment]
Hi, thanks for the interest. We use the OpenSSF instance for Google currently, so it is sound enough for serious use. That said it is a bit slow because of the number of installations, and has a 24-48 hour turnaround time, to close fixed issues for example.

As far as trust goes, you would be trusting me as the operator of the app. Currently I'm the only operator, but this is a volunteer based instance.

The admin:write is used to allow Allstar the "fix" action on Branch Protection. You can set your required settings, and Allstar will apply that to all your repos if they don't meet the minimum settings. The tutorial needs to be updated as the fix action was added later.

**Comment by ArisBee** [comment]
Thank you for your answer. Do you maybe have a document listing the type of data accessed by Allstar and how they are processed or stored on the instance?

If there isn't such document, an overview of what each permission is needed for would be very useful. For example, I couldn't know that Allstar needed an `admin:write permission` for "fix" action on Branch Protection.

**Comment by jeffmendoza** [comment]
We don't have a detailed doc, just the brief description here: https://github.com/ossf/allstar#installation-options Of course the code is open source, and could be searched/indexed for api calls, but I understand how an overview would be very helpful. I do believe we are asking for more read permissions than required with the expectation that we can implement new policies in the future.
