### ISSUE TITLE
Proposal: New policy for repo admins

### ISSUE THREAD

**Issue by coheigea** [ossf/allstar#358]
I'd like to propose a new policy for repo admins (although I'm open to any other ideas) to be able to enforce some things we'd like to be able to monitor/control with allstar:

- bool ownerlessAllowed: OwnerlessAllowed defined if repositories are allowed to have no administrators, default false. This is copied from the outside collaborators policy, as IMO it belongs here as it's nothing to do with outside collaborators.
- bool userAdminsAllowed: Whether to allow users to be admins on a repo. If false then only teams can be admins. Default true.
- int maxNumberUserAdmins: Maximum number of user admins on a repo
- bool teamAdminsAllowed: Whether to allow teams to be admins on a repo. If false then only users can be admins. Default true.
- int maxNumberAdminTeams: Maximum number of teams with admin rights on a repo.

Also I'd add an exemption list to allow individual exemptions at the org level per-repo. Any feedback welcome.

**Comment by jeffmendoza** [comment]
Sounds great. Maybe it would  good to propose the config structs/yamls for the new policy as well, and include the comment/documentation for each field to work through the logic.

I had included [`testingOwnerlessAllowed`](https://github.com/ossf/allstar/blob/main/pkg/policies/outside/outside.go#L80) in the "Outside Collaborator" policy, but a new separate policy makes sense. Because it is "testing" it would be ok to remove from that policy and include in a new admins policy.

**Comment by coheigea** [comment]
It would be nice too have:

- int maxNumberMembersPerAdminTeam: The maximum number of members in a team with admin permissions on a repo that are allowed.

However, MembersCount returns 0 as per https://github.com/google/go-github/issues/1252.
