### ISSUE TITLE
Feature: GitHub installation allowlist

### ISSUE THREAD

**Issue by raghavkaul** [ossf/allstar#365]
## Description

Allstar should allow the Operator to configure an allowlist of repositories/organizations that it can be installed on. If it detects an installation of the GitHub app on a repository that's not in this allowlist, it should skip the repository or deactivate the installation.

## What is the current behavior?

Today, Allstar instances that are published on the GitHub app marketplace as public apps can be installed by anyone. To privately install Allstar (e.g. enterprise), the operator must create a private app installation per GitHub organization, which is time consuming for operators with lots of GitHub organizations to manage. This may lead to mixing of public repo contents and 'enterprise' repo contents the operator intends to use Allstar on.

**Comment by jeffmendoza** [comment]
This makes sense, as you mentioned there are a couple ways to go about this.

>  it should skip the repository or deactivate the installation.

- _Skipping_: in the [enforce loop](https://github.com/ossf/allstar/blob/main/pkg/enforce/enforce.go#L87) Allstar could lookup the org for each installation and skip any not on the allow list.
- _Uninstall_: If Allstar is installed on any org not on the allow list, it can [uninstall itself](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#delete-an-installation-for-the-authenticated-app). The question here is when to do this:
  - This could be a part of the enforce loop as the skipping above.
  - A separate go routine that is kicked off every so often that loops through all installations.
  - A totally separate binary that is run as a job  by the environment. In this case it is a generic GitHub App allowlist tool, that doesn't need to be a part of Allstar.
  - An uninstaller that reacts to an install webhook. This would be the most reactive option, but we don't have a webhook listener currently. The code in cmd/reviewbot is not currently used, but could be a start.

Another consideration is how to provide the allowlist. Currently everything in pkg/config/operator is either hard coded or an environment variable. This could be an env var, but I could also see it being a file on disk.

Again, overall this sounds good, but let us know which directions you are thinking on the points above.

**Comment by azeemshaikh38** [comment]
Uninstalling the org would be preferable. Reason being that having the app installed on an outside org implies having access to that org's data through access tokens which is not something we're comfortable with. 

Secondly, would be good to have this as a file/config on disk. I expect the list of orgs to change and being able to update this easily (and keep track of the current list of allowed orgs) would be a huge plus. 

As to the question of when: ideally, as soon as a new installation is detected. But since webhooks are not yet supported, doing this as part of the regular enforce loop would be a good enough starting point. 

Let us know what you think. Also, happy to contribute to the implementation here.

**Comment by jeffmendoza** [comment]
All sounds good. Looks like a check and uninstall directly in the enforce loop meets the most desired requirements without setting up webhooks.

> Also, happy to contribute to the implementation here.

Sounds good.

Also, for the list source, consider  https://gocloud.dev/howto/runtimevar/ Which might be easier than a file. Feel free to add whichever options works best for your environment.
