### ISSUE TITLE
How to use allstar to actually look into a specific branch in a repository

### ISSUE THREAD

**Issue by bhuvi11** [ossf/allstar#42]
Hello @jeffmendoza,

Is there a possibility that I can look for a specific branch which using allstar?
Assume i have two different branch ,
Main and dev

Main branch as Security.md file and dev doesnt have.
Does allstar detect this and raise an issue?

Please help me understand 

Thanks in advance

**Comment by jeffmendoza** [comment]
Each policy is different. For example, the branch protection policy has a setting to look at the default branch (boolean) then you can specify a list of other branches to check as well.

Security.md only looks at default, as this is what is needed because that is what you see when you simply visit a repo on github.
